### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Wertzui123** [JackNoordhuis/DiscordRelay-PocketMine#4]
Do I have to create a bot? Because I don't now how!

**Comment by Xenophilicy** [comment]
@Wertzui123, it's actually a quite simple task to complete. If you're unsure of how, use a tutorial such as the one listed below. But to answer your question, yes, you must use a Discord bot. But since it's so simple, I'm sure you'll have no issues with it after that.

[Click here for tutorial!](https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/)

Hope this helps! 👍

**Comment by Wertzui123** [comment]
But I don't wan't to pay for hosting it...

**Comment by Xenophilicy** [comment]
You can host a Discord bot at your house, or even a friend can run it for you. All you need is the token from it. The plugin uses it as a host for "relaying" messages to and from Discord. All of this can be done for free

**Comment by Wertzui123** [comment]
Ok.

**Comment by JackNoordhuis** [comment]
The plugin itself is the bot, as @Xenophilicy said, all you need is the token once you have set everything up with discord.

**Comment by Wertzui123** [comment]
Oh ok thanks
